In [238]:
f1 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/김가연1.txt','r')

In [239]:
import numpy as np

In [240]:
ffts = []
datas = []

for line in f1:
    if line[0] == '-':
        ffts.append(datas)
        datas = []
    else:
        data = line.strip().split(',')
        #print(data)
        if data[0] != '':
            data = np.array(data, dtype=np.int)
            datas.append(data)
    i += 1

In [241]:
ffts = np.array(ffts)

In [242]:
ffts

array([ list([array([166, 151, 115, 117, 116, 113, 116, 125, 147, 141, 119,  86,  99,
        98, 120, 118,  98, 123, 125, 106,  79,  71,  90,  84,  84,  97,
       103,  89,  84,  60, 105, 104, 107,  89,  88,  96,  80,  67,  53,
        58,  46,  51,  49,  37,  37,  51,  59,  72,  61,  16,  45,  35,
        35,  33,  30,  47,  41,  33,  41,  16,   8,  30,  37,  35,  45,
        35,   0,  24,  27,  33,  43,  16,  19,  27,  19,   8,  19,  25,
         8,  16,   0,  24,   0,  24,   0,   0,  27,   8,  25,  19,  30,
         8,   8,   0,  19,   0,  19,   0,  19,   0,  19,   0,  16,  25,
         0,  19,  19,   0,   8,   0,  24,   8,  25,  16,  27,   0,   0,
        16,  19,   8,  19,  19,   0,   0,   0,  19,   0,  19, 176]), array([ 91,  90,  94,  86,  81,  86,  81,  70,  85,  43,  66,  73,  59,
        80,  59,  56,  59,   8,  46,  19,  54,  66,  49,  35,  42,  30,
        16,  63,  60,  65,  61,  51,   0,  27,  47,  30,  43,  45,  25,
        48,  46,  24,  43,   8,  19,   0,  41,  24,  

In [243]:
ffts30=np.zeros((3,30,129))
for i in range(len(ffts)):
    if np.shape(ffts[i])[0] == 32:
        ffts30[i]=ffts[i][1:-1]
    elif np.shape(ffts[i])[0] == 33:
        ffts30[i]=ffts[i][1:-2]
    elif np.shape(ffts[i])[0] == 31:
        ffts30[i]=ffts[i][1:]
    

In [244]:
np.shape(ffts30)

(3, 30, 129)

In [245]:
ffts30

array([[[  91.,   90.,   94., ...,   16.,    0.,  204.],
        [  82.,   40.,   69., ...,    8.,    0.,  221.],
        [ 108.,   93.,   80., ...,    0.,   27.,  148.],
        ..., 
        [ 104.,   97.,   75., ...,    8.,    0.,  166.],
        [ 104.,   95.,   72., ...,    0.,    8.,  166.],
        [  97.,   88.,   58., ...,    8.,    8.,  189.]],

       [[  96.,   71.,   90., ...,    8.,   16.,  191.],
        [  93.,   82.,   70., ...,    0.,   24.,  200.],
        [  93.,   80.,   95., ...,    0.,    8.,  200.],
        ..., 
        [  95.,   89.,   60., ...,    0.,    0.,  194.],
        [ 106.,   79.,   93., ...,   24.,   19.,  156.],
        [  97.,   89.,   74., ...,    8.,   16.,  188.]],

       [[  87.,   75.,   79., ...,    0.,   19.,  213.],
        [  81.,   90.,   91., ...,    0.,   19.,  223.],
        [  83.,   91.,   88., ...,    0.,   30.,  220.],
        ..., 
        [  82.,   35.,   84., ...,   16.,   16.,  221.],
        [  98.,   83.,   99., ...,    0., 

In [246]:
np.save('C:/Users/User/PycharmProjects/AIproject2/인프데이터/정종우1.npy',ffts30)

In [200]:
data = np.load('C:/Users/User/PycharmProjects/AIproject2/인프데이터/강형원1.npy')

In [201]:
np.shape(data)

(3, 30, 129)

In [289]:
data1 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/강형원_test.txt','r')
data2 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/김가연_test.txt','r')
data3 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/이전우_test.txt','r')
data4 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/전한별_test.txt','r')
data5 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/정기평_test.txt','r')
data6 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/정종우_test.txt','r')

In [290]:
data = [data1,data2,data3,data4,data5,data6]
ffts = []
datas = []

for i in data:
    for line in i:
        d = line.strip().split(',')
        if d != '':
            d = np.array(d, dtype=np.int)
            datas.append(d)
    datas = np.array(datas, dtype=np.int)
    ffts.append(datas)
    datas = []

In [291]:
ffts = np.array(ffts)

In [293]:
ffts30=np.zeros((6,30,129))
for i in range(len(ffts)):
    if np.shape(ffts[i])[0] == 32:
        ffts30[i]=ffts[i][1:-1]
    elif np.shape(ffts[i])[0] == 33:
        ffts30[i]=ffts[i][1:-2]
    elif np.shape(ffts[i])[0] == 31:
        ffts30[i]=ffts[i][1:]

In [295]:
np.shape(ffts30)

(6, 30, 129)

In [296]:
labels = [1,2,3,4,5,6]
labels = np.array(labels, ndmin=2, dtype=np.int).T


In [297]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit(labels)
ohe.n_values_,ohe.feature_indices_,ohe.active_features_
labels = ohe.transform(labels).toarray()
print(labels)

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function n_values_ is deprecated; The ``n_values_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function feature_indices_ is deprecated; The ``feature_ind

In [298]:
np.save('C:/Users/User/PycharmProjects/AIproject2/인프데이터/data_test.npy',ffts30)
np.save('C:/Users/User/PycharmProjects/AIproject2/인프데이터/labels_test.npy',labels)