In [23]:
import numpy as np

data1 = np.load('C:/Users/User/PycharmProjects/AIproject2/인프데이터/강형원_data1.npy')
data2 = np.load('C:/Users/User/PycharmProjects/AIproject2/인프데이터/김가연_data1.npy')
data3 = np.load('C:/Users/User/PycharmProjects/AIproject2/인프데이터/이전우_data1.npy')
data4 = np.load('C:/Users/User/PycharmProjects/AIproject2/인프데이터/전한별_data1.npy')
data5 = np.load('C:/Users/User/PycharmProjects/AIproject2/인프데이터/정기평_data1.npy')
data6 = np.load('C:/Users/User/PycharmProjects/AIproject2/인프데이터/정종우_data1.npy')

In [7]:
labels1 = np.zeros([1,240])
labels2 = np.ones([1,240])
labels3 = np.ones([1,240]) * 2
labels4 = np.ones([1,240]) * 3
labels5 = np.ones([1,240]) * 4
labels6 = np.ones([1,240]) * 5

In [36]:
labels = np.hstack((labels1, labels2, labels3, labels4, labels5, labels6))

In [37]:
labels = labels[0]

In [39]:
labels = np.array(labels, ndmin=2, dtype=np.int).T

In [40]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit(labels)
ohe.n_values_,ohe.feature_indices_,ohe.active_features_
labels = ohe.transform(labels).toarray()
print(labels)

[[ 1.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 ..., 
 [ 0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.]]


C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function n_values_ is deprecated; The ``n_values_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:77: DeprecationWarning: Function feature_indices_ is deprecated; The ``feature_ind

In [28]:
data = np.vstack((data1, data2, data3, data4, data5, data6))

In [29]:
np.shape(data)

(1440, 30, 129)

In [41]:
np.save('C:/Users/User/PycharmProjects/AIproject2/인프데이터/data_train.npy',data)
np.save('C:/Users/User/PycharmProjects/AIproject2/인프데이터/labels_train.npy',labels)

In [43]:
data1 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/강형원_test.txt','r')
data2 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/김가연_test.txt','r')
data3 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/이전우_test.txt','r')
data4 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/전한별_test.txt','r')
data5 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/정기평_test.txt','r')
data6 = open('C:/Users/User/PycharmProjects/AIproject2/인프데이터/정종우_test.txt','r')